title: Alexander<br>Levin-Koopman # your name (or website title) here
logo: "/images/profile_image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  As a lecturer in Applied Data Science at the University of Michigan School of Information, 
  I'm passionate about empowering others to extract insights from complex data sets. With a 
  Master's degree in Applied Data Science (4.0 GPA) from the University of Michigan and a 
  Bachelor's degree in Mathematics from the University of Colorado at Boulder, I've developed 
  a strong foundation in statistical analysis, machine learning, and data visualization. 
  <br>
  My academic background has equipped me with a unique ability to approach problems from multiple angles, 
  think creatively, and communicate complex ideas effectively. While my experience is rooted in academia, 
  I'm eager to apply my skills in a real-world setting and drive business outcomes through data-driven 
  decision making. 
  <br>
  I thrive on solving intricate problems and uncovering hidden patterns in data. My goal is to leverage 
  my expertise to inform strategic decisions, optimize processes, and create value for organizations. 
  If you're looking for a driven and analytical problem-solver who is passionate about data science, 
  let's connect! <br>
  <br>
  <a href="https://www.linkedin.com/in/alexander-levin-koopman-550522188/">View My LinkedIn Profile</a>
  <br>
  <a href="https://github.com/Alkoopman85/">View My GitHub Profile</a>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
